"""Run signals A/B(/C) over a RAGTruth split and write a fusion features CSV.

For each summary sentence: classifier (A), NLI (B), and optionally attribution (C)
scores + the grounded gold label. Output feeds scripts/train_fusion.py.

Attribution is off by default: RAGTruth summaries were not generated by our local
model, so Inseq attribution is not well-defined for them (see research-plan.md §8).
Enable with --with-attribution only when summaries come from our own summariser.

This runs the REAL models — launch on HPC (si-gpu / sbatch), not in CI.
"""

import argparse
import csv
from pathlib import Path

from sumlens.eval.features import FIELDNAMES, feature_rows
from sumlens.eval.ragtruth import load_split
from sumlens.signals.attribution import attribute
from sumlens.signals.classifier import classify
from sumlens.signals.nli import entail, extract_claims
from sumlens.types import AnalysisConfig


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data/ragtruth"))
    parser.add_argument("--split", default="train")
    parser.add_argument("--out", type=Path, default=Path("features.csv"))
    parser.add_argument("--with-attribution", action="store_true")
    parser.add_argument("--limit", type=int, default=0, help="cap summaries (0 = all)")
    args = parser.parse_args()

    cfg = AnalysisConfig()
    examples = load_split(args.split, data_dir=args.data_dir)
    if args.limit:
        examples = examples[: args.limit]

    rows: list[dict[str, object]] = []
    for document, summary, hallucinated in examples:
        classifier_out = classify(document, summary, cfg)
        nli_out = entail(extract_claims(summary), document, cfg)
        attribution_out = attribute(document, summary, cfg) if args.with_attribution else {}
        rows.extend(
            feature_rows(summary, hallucinated, classifier_out, nli_out, attribution_out)
        )

    with args.out.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {args.out} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
