"""Run signals A/B/C over a RAGTruth split and write a fusion features CSV.

For each summary sentence: classifier (A), NLI (B), and support attribution (C =
attr_conc + attr_loo) scores + the grounded gold label. Output feeds the ablation.

Signal C here is the generator-agnostic support attribution (signals/support.py),
derived from an NLI matrix, so it is well-defined for RAGTruth even though those
summaries were not generated by our local model (unlike Inseq attribution; see
research-plan.md §8). It therefore always runs.

This runs the REAL models — launch on HPC (si-gpu / sbatch), not in CI.
"""

import argparse
import csv
from pathlib import Path

from sumlens.eval.features import FIELDNAMES, feature_rows
from sumlens.eval.ragtruth import load_split
from sumlens.signals.classifier import classify
from sumlens.signals.nli import entail, extract_claims
from sumlens.signals.support import support_attribution
from sumlens.types import AnalysisConfig


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data/ragtruth"))
    parser.add_argument("--split", default="train")
    parser.add_argument("--out", type=Path, default=Path("features.csv"))
    parser.add_argument("--limit", type=int, default=0, help="cap summaries (0 = all)")
    args = parser.parse_args()

    cfg = AnalysisConfig()
    examples = load_split(args.split, data_dir=args.data_dir)
    if args.limit:
        examples = examples[: args.limit]

    rows: list[dict[str, object]] = []
    for document, summary, hallucinated in examples:
        classifier_out = classify(document, summary, cfg)
        nli_out = entail(extract_claims(summary), document, cfg)
        support_out = support_attribution(document, summary, cfg)
        rows.extend(
            feature_rows(summary, hallucinated, classifier_out, nli_out, support_out)
        )

    with args.out.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {args.out} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
